### ISSUE TITLE
Testing model with data apart from test data

### ISSUE THREAD

**Issue by rob-hooke** [MichaelE919/machine-learning-predict-weather#2]
Hi Michael,

Wonder explanation about the project as well as the code. I needed to get one thing clarified, you are building say a LR model and testing it against the test set. How would you go about predicting temperature of future dates? 

I may be wrong here also as I'm thinking this code needs to run on each day so that the updated data needs to be pulled from the API, then build the model again for prediction, right?

**Comment by MichaelE919** [comment]
@nemesisBR Yeah, I think you are on the right track. I meant to return to this project and work on some actual prediction scenarios but Wunderground.com retired their API. I now need to rewrite the collect_weather.py and weather.py modules to connect to another API. When I'm able to get around to that I'll definitely explore predicting future dates.

**Comment by rob-hooke** [comment]
Yeah, even I had to search for free APIs.
